Repository ankit071105/Ticket-Booking, pull requests merged in 2024-11, with the labels that each got.

#834 created a separate FAQ web page
  Faq.html
  about.html
  buy.html
  contactus.html
  contributor.html
  index.html
  login.html
  sell.html
Labels: level2, gssoc-ext

#830 Scroll back button for the contact us section
  contactus.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#797 Sell section resolved the bug
  contactus.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#836 fixed gap, added home link, added same navbar for all pages
  about.html
  buy.html
  contactus.html
  contributor.html
  index.html
  styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#843 sell bus ticket page resolved
  sell.html
  train_sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#865 Updated the readme file
  README.md
  images/GSSoC-Ext.png
  images/hacktoberfest.png
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#869 Created ATOL and ABTA Pages
  abta.html
  atol.html
  images/ABTA.png
  images/atol.png
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#870 Fix issue no. #782 Add some effects on map.
  index.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#874 FAQ Page Fixed
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#877 Changed the file opening for sell train tickets. Fixed #810
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#883 buy ticket page dark mode update
  buy.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#892 Added Trusted email validation functionality in contact us form
  contactus.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#895 organised the header
  header.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#897 Enchancing the Book_condition.html
  book_condition.html
  forgot_password.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#866 toggle button in Contributor page added succesfully.
  contributor.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#867 Toggle button in About Page
  about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#931 Added the follow links which were missing in the footer
  fcdoTravel.html
  privacy.html
  travelAware.html
Labels: level1, gssoc-ext

#928 Privacy Footer Page Updated
  privacy.html
Labels: level1, gssoc-ext

#932 Changes the color of the heading tag in dark mode of home page
  contributor.css
  index.css
Labels: level1, gssoc-ext

#905 Add visitor count
  index.html
  server/app.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#881 Added a new page for AI suggestions
  AI suggestions.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#899 Similar Top scroll button on every page
  about.html
  contact.html
  contactus.html
  contributor.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#936 Add a User Profiles page done ! #875
  index.html
  styles.css
  testp.css
  testp.html
  testp.js
Labels: level1, gssoc-ext

#942 Unnecessary code Leak #924
  contactus.html
Labels: level1, gssoc-ext

#945 Added Close button for voteBox
  index.html
Labels: level1, gssoc-ext

#991 The double button in Abouts page #984
  about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#998 🛠️FIX : Missing mouse animation added
  contactus.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1000 🛠️FIX : Contact us page name and email field validation added
  contactus.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1003 CHANGED the Slider Button Position and changed the DOTS COLOR making it GOOD LOOKING
  index.css
  index.html
  main.css
  styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1004 FIXED the OVER-SIZING of Social SIDE-BAR
  main.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1005 Make buy page responsive
  buy.html
  index.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1050 🐛[FIX] : Star color is not visible
  index.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#1051 feat(ui): Beautify registration form
  register.html
  styles.css
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#1054 fix: Remove Duplicate Footer Section for Cleaner Codebase
  contactus.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#1082 Fix Footer in FAQ page done ! #1073
  footer.css
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#1085 Add Footer in Terms of use page done ! #1076
  terms.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#1081 Add Edit Profile Feature in Profile Page done ! #994
  index.html
  profileedit.html
  testp.html
  testp.js
Labels: bug, level3, gssoc-ext, hacktoberfest-accepted

#1093 Added Dynamic Copyright Year in Check Availability Page
  check_availability.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#853 To adding the animation effect to social media icons
  about.html
  buy.html
  contactus.html
  contributor.html
  footer.css
  index.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#938 login page resolved
  index.html
  login.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#939 Register page done
  register.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#968 contactus page with the new look
  contactus.html
Labels: bug

#977 Register page toggle button added
  index.html
  register.html
Labels: bug

#1119 change ui of nav bar menus
  index.html
Labels: level1, gssoc-ext

#1120 sell.html is improved
  footer.css
  sell.html
Labels: level1, gssoc-ext

#1121 UPDATED Feedback Form
  index.html
Labels: level1, gssoc-ext

#1122 Fixed the BUG of Register Page
  register.html
Labels: level1, gssoc-ext

#1123 Fixed the Double Profiles Problem in Menubar
  index.html
Labels: level1, gssoc-ext

#1124 static icons animation added and appropriate color on hovering added
  main.css
Labels: level1, gssoc-ext

#1125 CHANGED the ABOUT US Section View
  about.html
Labels: level1, gssoc-ext
