Repository ankit071105/Ticket-Booking, pull requests merged in 2024-10, with the labels that each got.

#7 logo is added
  index.html
Labels: enhancement, gssoc

#61 Added Signup button on navbar
  client/login.html
  client/register.html
  index.html
Labels: gssoc, Level 1

#91 Add logos
  buy.html
  index.css
  index.html
  sell.html
  styles.css
  train_buy.html
  train_sell.html
Labels: gssoc-ext, hacktoberfest-accepted

#170 Signup via google firebase enabled
  client/login.html
  client/register.html
  firebase.js
  images/googleLogo.png
  index.css
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#307 added email functionality
  Ticket-Booking-main1/client/package-lock.json
  Ticket-Booking-main1/index.html
  Ticket-Booking-main1/server/.gitignore
  server/app.js
  server/config/db.js
  server/controllers/v1/auth_controller.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#393 update social media icon
  buy.html
  index.html
  sell.html
  train_buy.html
  train_sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#460 FIXED - Non-Redirecting "Top Hotels" Footer Link
  buy.html
  index.html
  sell.html
  tophotels.html
  train_buy.html
  train_sell.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#480 Seperated Css files that creates an error
  main.css
Labels: level2, level3, gssoc-ext

#510 Login with Google is not working
  client/login.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#525 solved #469
  Ticket-Booking-main1/index.css
  index.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#518 change sell tickets
  styles.css
  train_sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#517 transform feedback section.
  index.css
  index.html
  main.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#516 created pr-checker
  .github/workflows/pr-checker.yml
Labels: level1, gssoc-ext, hacktoberfest-accepted

#515 FIXED : [BUG] Ticket booking icon the footer not functional #485
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#514 fixed horizontal scrolling
  index.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#545 Changed UI of Contributions page + made the navigation bar uniform #492
  about.html
  buy.html
  contributor.css
  contributor.html
  contributor.js
  contributor/4.jpeg
  contributor/contributor.html
  index.html
  sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#544 solved #470
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#541 faq bug Sloved Issue #536
  faq.css
  faq.js
  index.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#539 Modified the ui of the buyticket page
  buy.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#538 This PR is related to issue #495.Terms of use page created.
  index.html
  styles.css
  terms.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#532 "carousel and carousel button issue fixed"
  index.css
  index.html
  main.css
  styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#511 Enhanced the UI of sell ticket page
  images/train-img.jpeg
  sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#578 Fixes #540
  Contribution.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#605 #567-chatbot-fixed
  chatbot.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#634 Fix issue:609 Adding Contact us page
  about.html
  book_condition.html
  buy.html
  contactus.html
  contributor.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#641 Implement Robust Error Handling and Performance Optimizations in Ticket Management System
  app.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#646 Working chatbot icon
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#644 Added animations and smooth scroll to faq section
  faq.css
  faq.js
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#668 made buys section responsive
  buy.html
  styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#671 Added improved version of our review section
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#672 twitter logo changed
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#674 Aligned the items in the sell section
  sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#675 ui improvement of travel awareness page
  index.html
  travelAware.html
  travelawares.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#681 toggle button added
  index.html
  navbar.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#684 Created GroupCookieNotice and SiteMap Pages
  GroupCookieNotice.html
  index.html
  sitemap.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#685 Added a navbar to the contact us form.
  contactus.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#688 Update README.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#602 Added a contact page
  contact.html
  index.css
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#706 Fixes #610: Added FCOD travel advice page
  Contribution.md
  buy.html
  contact.html
  fcdoTravel.html
  index.html
  login.html
Labels: help wanted, hacktoberfest-accepted

#713 Added a scroll back button to main page
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#717 Removed the white space between navbar and the slider
  index.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#725 changed corousel next and prev
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#735 added a pre-loader to the website
  index.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#743 [BUG FIX] Resolved Chatbot Submit Button Styling Issue (#647)
  .gitignore
  123
  eval $(ssh-agent -s)
  eval $(ssh-agent -s).pub
  index.html
  main.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#738 Fix Duplicate Navbar Display Issue on Sell Page
  sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#718 footer link of all pages are now working
  GroupCookieNotice.html
  ModernSlaveryAct.html
  about.html
  buy.html
  contact.html
  contactus.html
  contributor.html
  help.html
  pnr_check.html
  privacy.html
  quota.html
  seatAvail.html
  sell.html
  sitemap.html
  terms.html
  tophotels.html
  train_buy.html
  train_sell.html
  travelAware.html
  travelawares.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#747 Contact form created
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#749 [BUG FIX] Resolved Chatbot Submit Button Styling Issue #743
  .gitignore
  123
  eval $(ssh-agent -s)
  eval $(ssh-agent -s).pub
Labels: level1, gssoc-ext, hacktoberfest-accepted

#751 Fixed move to top button
  index.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#765 Add day/night mode functionality to enhance appearance and remove any excess elements for a cleaner look.
  images/ios_logo.png
  images/playstore_logo.png
Labels: level1, gssoc-ext, hacktoberfest-accepted

#774 Fixes #553 : Fixed the contributors and Total Contributions data
  contributor.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#777 scroll back button for the about us section
  about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#780 footer of contact page updated
  contactus.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#794 Resolved FAQ section collision with footer
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#808 sell page improved
  sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#784 Rating section enhancement
  contactus.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#820 Created a check-availability page for buy ticket section
  buy.html
  check_availability.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#819 Transformation
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#818 Fix Cursor Trail Effect During Scroll Events
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#817 I separated the FAQ and Footer section in the home page.
  index.css
  index.html
  main.css
  test.html
  test2.htm
  test4.htm
Labels: level1, gssoc-ext, hacktoberfest-accepted

#811 Add a pop up dialog box for Polls/Survey done ! #759🌟🌟🌟
  index.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#807 sell train ticket page header resolved
  train_sell.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#802 [BUG] `Home Page` Elements are no more Concinding over other
  faq.css
Labels: level1, gssoc-ext, hacktoberfest-accepted
